import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Button from "@/components/common/Button";
import Card from "@/components/common/Card";

const data = [
  {
    id: 676,
    title: "test 4 sale 4",
    address: "Stevens Pass, U.S. 2, Skykomish, WA, USA",
    slug: "test-4-sale-4",
    price_per_night: 130,
    price_per_month: 1500,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/676/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/676/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/676/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/676/image-4.peg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/676/image-5.jpg",
    ],
    city: "Skykomish",
    state: "Washington",
    airport: {
      name: "Stevens Village Airport",
      ICAO: "SVS",
      coordinates: "-149.0545, 66.0172",
    },
  },
  {
    id: 675,
    title: "test 2 sale 2",
    address: "Sparrevohn Engineering, East 11th Street, Long Beach, CA, USA",
    slug: "test-2-sale-2",
    price_per_night: 100,
    price_per_month: 1000,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/675/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/675/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/675/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/675/image-4.peg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/675/image-5.jpg",
    ],
    city: "Long Beach",
    state: "California",
    airport: {
      name: "Sparrevohn LRRS Airport",
      ICAO: "PASV",
      coordinates: "-155.5740051, 61.09740067",
    },
  },
  {
    id: 674,
    title: "24-03-24",
    address: "1535 NW 5th St, Oklahoma City, OK 73107, USA",
    slug: "24-03-24",
    price_per_night: 250,
    price_per_month: 2500,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-5.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-6.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-7.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-8.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/674/image-9.jpg",
    ],
    city: "Oklahoma City",
    state: "Oklahoma",
    airport: {
      name: "El Centro NAF Airport (Vraciu Field)",
      ICAO: "KNJK",
      coordinates: "-115.671996, 32.829201",
    },
  },
  {
    id: 673,
    title: "Test sell price",
    address:
      "Harvey Point Defense Testing Activity, Harvey Point Road, Hertford, NC, USA",
    slug: "test-sell-price",
    price_per_night: 100,
    price_per_month: 3000,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/673/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/673/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/673/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/673/image-4.peg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/673/image-5.jpg",
    ],
    city: "Hertford",
    state: "North Carolina",
    airport: {
      name: "Harvey Point Defense Testing Activity Airport",
      ICAO: "NC01",
      coordinates: "-76.32710266113281, 36.09619903564453",
    },
  },
  {
    id: 672,
    title: "20-03-24",
    address:
      "MNGI Digestive Health - Plymouth Endoscopy Center & Clinic, 37th Avenue North, Plymouth, MN, USA",
    slug: "20-03-24",
    price_per_night: 70,
    price_per_month: 50,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-5.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-6.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-7.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-8.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/672/image-9.jpg",
    ],
    city: "Plymouth",
    state: "Minnesota",
    airport: {
      name: "El Centro NAF Airport (Vraciu Field)",
      ICAO: "KNJK",
      coordinates: "-115.671996, 32.829201",
    },
  },
  {
    id: 671,
    title: "19-03-24",
    address: "1Mosaic Church, West Maple Avenue, Adrian, MI, USA",
    slug: "19-03-24",
    price_per_night: 50,
    price_per_month: 10,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-5.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-6.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-7.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-8.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/671/image-9.jpg",
    ],
    city: "Adrian",
    state: "Michigan",
    airport: {
      name: "Rustic Wilderness Airport",
      ICAO: "02AK",
      coordinates: "-150.09800720214844, 61.87689971923828",
    },
  },
  {
    id: 670,
    title: "18-03-24",
    address: "JK by Chef King, North Robinson Avenue, Oklahoma City, OK, USA",
    slug: "18-03-24",
    price_per_night: 50,
    price_per_month: 10,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/670/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/670/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/670/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/670/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/670/image-5.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/670/image-6.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/670/image-7.jpg",
    ],
    city: "Oklahoma City",
    state: "Oklahoma",
    airport: {
      name: "El Centro NAF Airport (Vraciu Field)",
      ICAO: "KNJK",
      coordinates: "-115.671996, 32.829201",
    },
  },
  {
    id: 669,
    title: "gerogtown hangar",
    address:
      "Skin Boutique by Angelique, South Rock Street, Georgetown, TX, USA",
    slug: "gerogtown-hangar",
    price_per_night: 123,
    price_per_month: 12,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/669/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/669/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/669/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/669/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/669/image-5.jpg",
    ],
    city: "Georgetown",
    state: "Texas",
    airport: {
      name: "Flying Crown Airport",
      ICAO: "AK12",
      coordinates: "-149.86399841308594, 61.10660171508789",
    },
  },
  {
    id: 668,
    title: "test title drag",
    address: "17 Sycamore Terrace, Springfield, NJ 07081, USA",
    slug: "test-title-drag",
    price_per_night: 12,
    price_per_month: 123,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/668/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/668/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/668/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/668/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/668/image-5.jpg",
    ],
    city: "Springfield",
    state: "New Jersey",
    airport: {
      name: "Flying Crown Airport",
      ICAO: "AK12",
      coordinates: "-149.86399841308594, 61.10660171508789",
    },
  },
  {
    id: 666,
    title: "140324",
    address: "JK Kabab, Weston Ridge Drive, Naperville, IL, USA",
    slug: "140324",
    price_per_night: 50,
    price_per_month: 50,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/666/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/666/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/666/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/666/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/666/image-5.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/666/image-6.jpg",
    ],
    city: "Naperville",
    state: "Illinois",
    airport: {
      name: "El Centro NAF Airport (Vraciu Field)",
      ICAO: "KNJK",
      coordinates: "-115.671996, 32.829201",
    },
  },
  {
    id: 665,
    title: "140324",
    address: "JK Kabab, Weston Ridge Drive, Naperville, IL, USA",
    slug: "140324",
    price_per_night: 50,
    price_per_month: 50,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/665/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/665/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/665/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/665/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/665/image-5.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/665/image-6.jpg",
    ],
    city: "Naperville",
    state: "Illinois",
    airport: {
      name: "Jack Edwards Airport",
      ICAO: "KJKA",
      coordinates: "-87.67179871, 30.29050064",
    },
  },
  {
    id: 664,
    title: "14-03-24",
    address: "JK Kabab, Weston Ridge Drive, Naperville, IL, USA",
    slug: "14-03-24",
    price_per_night: 50,
    price_per_month: 40,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/664/image-1._01",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/664/image-2._00",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/664/image-3._02",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/664/image-4._03",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/664/image-5._04",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/664/image-6._05",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/664/image-7._06",
    ],
    city: "Naperville",
    state: "Illinois",
    airport: {
      name: "El Centro NAF Airport (Vraciu Field)",
      ICAO: "KNJK",
      coordinates: "-115.671996, 32.829201",
    },
  },
  {
    id: 663,
    title: "tax test hangar georgetown",
    address:
      "Georgetown Municipal Airport, Terminal Drive, Georgetown, TX, USA",
    slug: "tax-test-hangar-georgetown",
    price_per_night: 100,
    price_per_month: 600,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/663/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/663/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/663/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/663/image-4.peg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/663/image-5.jpg",
    ],
    city: "Georgetown",
    state: "Texas",
    airport: {
      name: "Georgetown Municipal Airport",
      ICAO: "KGTU",
      coordinates: "-97.67939758300781, 30.678800582885742",
    },
  },
  {
    id: 662,
    title: "Tax test hangar georgetown",
    address: "Georgetown, Bowie Street, Austin, TX, USA",
    slug: "tax-test-hangar-georgetown",
    price_per_night: 100,
    price_per_month: 600,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/662/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/662/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/662/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/662/image-4.peg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/662/image-5.jpg",
    ],
    city: "Austin",
    state: "Texas",
    airport: {
      name: "Columbia Gorge Regional the Dalles Municipal Airport",
      ICAO: "KDLS",
      coordinates: "-121.166999817, 45.6184997559",
    },
  },
  {
    id: 661,
    title: "123asd asd",
    address: "123 William Street, New York, NY, USA",
    slug: "123asd-asd",
    price_per_night: 90,
    price_per_month: 900,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/661/image-1._00",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/661/image-2._01",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/661/image-3._02",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/661/image-4._03",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/661/image-5._04",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/661/image-6._05",
    ],
    city: "New York",
    state: "New York",
    airport: {
      name: "Flying Crown Airport",
      ICAO: "AK12",
      coordinates: "-149.86399841308594, 61.10660171508789",
    },
  },
  {
    id: 660,
    title: "12-03-24 testing",
    address: "J K O'Donnell's, West Wayne Street, Fort Wayne, IN, USA",
    slug: "12-03-24-testing",
    price_per_night: 60,
    price_per_month: 600,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/660/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/660/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/660/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/660/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/660/image-5.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/660/image-6.jpg",
    ],
    city: "Fort Wayne",
    state: "Indiana",
    airport: {
      name: "El Centro NAF Airport (Vraciu Field)",
      ICAO: "KNJK",
      coordinates: "-115.671996, 32.829201",
    },
  },
  {
    id: 659,
    title: "12--3-24 test",
    address: "JK by Chef King, North Robinson Avenue, Oklahoma City, OK, USA",
    slug: "12-3-24-test",
    price_per_night: 60,
    price_per_month: 600,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/659/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/659/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/659/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/659/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/659/image-5.jpg",
    ],
    city: "Oklahoma City",
    state: "Oklahoma",
    airport: {
      name: "El Centro NAF Airport (Vraciu Field)",
      ICAO: "KNJK",
      coordinates: "-115.671996, 32.829201",
    },
  },
  {
    id: 658,
    title: "12-03-24",
    address: "JK Kabab, Weston Ridge Drive, Naperville, IL, USA",
    slug: "12-03-24",
    price_per_night: 60,
    price_per_month: 600,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/658/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/658/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/658/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/658/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/658/image-5.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/658/image-6.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/658/image-7.jpg",
    ],
    city: "Naperville",
    state: "Illinois",
    airport: {
      name: "El Centro NAF Airport (Vraciu Field)",
      ICAO: "KNJK",
      coordinates: "-115.671996, 32.829201",
    },
  },
  {
    id: 657,
    title: "test test",
    address: "Raceway Mall Drive, Freehold, NJ, USA",
    slug: "test-test",
    price_per_night: 100,
    price_per_month: 1500,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/657/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/657/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/657/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/657/image-4.peg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/657/image-5.jpg",
    ],
    city: "Freehold",
    state: "New Jersey",
    airport: {
      name: "Raceway Airport",
      ICAO: "II32",
      coordinates: "-87.38140106201172, 38.049198150634766",
    },
  },
  {
    id: 652,
    title: "new req list",
    address: "123 Farm, Highland Springs Avenue, Beaumont, CA, USA",
    slug: "new-req-list",
    price_per_night: 1.01,
    price_per_month: 0,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/652/image-1._00",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/652/image-2._01",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/652/image-3._02",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/652/image-4._03",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/652/image-5._04",
    ],
    city: "Beaumont",
    state: "California",
    airport: {
      name: "Lowell Field",
      ICAO: "00AK",
      coordinates: "-151.695999146, 59.94919968",
    },
  },
  {
    id: 651,
    title: "new req list",
    address: "123 Farm, Highland Springs Avenue, Beaumont, CA, USA",
    slug: "new-req-list",
    price_per_night: 1.01,
    price_per_month: 0,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/651/image-1._00",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/651/image-2._01",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/651/image-3._02",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/651/image-4._03",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/651/image-5._04",
    ],
    city: "Beaumont",
    state: "California",
    airport: {
      name: "Lowell Field",
      ICAO: "00AK",
      coordinates: "-151.695999146, 59.94919968",
    },
  },
  {
    id: 650,
    title: "Test",
    address: "AAA Wholesale Cash & Carry, 49th Place, Queens, NY, USA",
    slug: "test",
    price_per_night: 200,
    price_per_month: 0,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/650/image-1.png",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/650/image-2.png",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/650/image-3.png",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/650/image-4.png",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/650/image-5.png",
    ],
    city: "aaaaa",
    state: "New York",
    airport: {
      name: "Lowell Field",
      ICAO: "00AK",
      coordinates: "-151.695999146, 59.94919968",
    },
  },
  {
    id: 648,
    title: "Hangar Test 5",
    address: "450 Sutter Street, Sutter Street, San Francisco, CA, USA",
    slug: "hangar-test-5",
    price_per_night: 40,
    price_per_month: 300,
    images: [
      "https://hangar-storage-2.s3.amazonaws.com/hangars/648/image-1.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/648/image-2.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/648/image-3.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/648/image-4.jpg",
      "https://hangar-storage-2.s3.amazonaws.com/hangars/648/image-5.jpg",
    ],
    city: "San Francisco",
    state: "California",
    airport: {
      name: "Flying W Ranch Airport",
      ICAO: "04AA",
      coordinates: "-150.811387, 60.535833",
    },
  },
 
];

const Home = () => {
  return (
    <div className="mb-16">
      {/* <Header /> */}

      <div className="wrapper px-[20px] xl:px-[56px] mb-16 flex flex-col gap-5 max-w-[100%] overflow-hidden">

      <div className="card-item flex flex-wrap justify-center md:gap-4 lg:gap-3 gap-4 w-[100%]">
        {data.map((item, index) =>(

          <Card {...{item}} />
    
        ))}
      </div>
      </div>
      {/* <Footer /> */}
    </div>
  );
};

export default Home;
